name: Build

on:
  workflow_call:
    inputs:
      channel:
        type: string
        description: Channel to build
        required: true
        default: 'dev'
  workflow_dispatch:
    inputs:
      channel:
        type: choice
        description: Select channel to build
        required: true
        options:
          - dev
          - rc
      custom-commit:
        type: string
        description: Custom commit
        required: false
      dry-run:
        type: choice
        description: Dry run
        required: false
        options:
          - false
          - true

run-name: Build ${{ inputs.channel }}

jobs:
  check:
    steps:
      - name: Block PR Builds
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "PRs may not trigger builds"
            exit 1
          fi

  prepare:
    needs: check
    steps: 
      - name: Pear
        run: npx pear && pear sidecar shutdown && echo "pear://3oh9mxcft8rsq3mocxzi7s8hhb7zw8s55nuca95ffsqzd6oyy4zo" > $(npm list -g pear --depth=0 --parseable)/pear.key && npx pear

  build:
    needs: prepare
    steps: 
      - name: Pear
        run: npx pear && pear sidecar shutdown && echo "pear://3oh9mxcft8rsq3mocxzi7s8hhb7zw8s55nuca95ffsqzd6oyy4zo" > $(npm list -g pear --depth=0 --parseable)/pear.key && npx pear
    uses: holepunchto/actions/.github/workflows/keet-automation.yml@v1
    secrets: inherit
    with:
      job: pear-electron
      channel: ${{ inputs.channel }}
      commit: ${{ inputs.custom-commit || github.sha }}
      dry-run: ${{ inputs.dry-run }}
