name: Build Status
on:
  schedule:
    - cron:  '0 10 * * *'
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          platform: linux
          arch: x64
        - os: macos-latest
          platform: darwin
          arch: x64
        - os: windows-latest
          platform: win32
          arch: x64
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - name: Setup repo
        uses: holepunchto/actions/.github/steps/setup-repo@v1

      - name: Install w/ dev deps
        run: npm install

      - name: Cache corestore
        uses: actions/cache@v4
        with:
          path: /tmp/pear-archdump
          key: ${{ matrix.os }}-corestore

      - name: Pear
        run: npx pear && pear sidecar shutdown && echo "pear://3oh9mxcft8rsq3mocxzi7s8hhb7zw8s55nuca95ffsqzd6oyy4zo" > $(npm list -g pear --depth=0 --parseable)/pear.key && npx pear 

      - name: Bootstrap
        run: npm run bootstrap

      - name: Lint
        run: npm run lint
