name: Build Status
on:
  schedule:
    - cron:  '0 10 * * *'
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          platform: linux
          arch: x64
        - os: macos-latest
          platform: darwin
          arch: x64
        - os: windows-latest
          platform: win32
          arch: x64
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - name: Lint
        run: npx standard --fix
